### ISSUE TITLE
DPDT-switch

### ISSUE THREAD

**Issue by mattip123** [HSBallina/ecad-models#2]
Would be great with a DPDT-switch as well as the SPDT-switch!

**Comment by HSBallina** [comment]
@mattip123 Will add a DPDT shortly

**Comment by HSBallina** [comment]
@mattip123 Let me know if it works ok :)

**Comment by mattip123** [comment]
Great! I like that the anchor is in the middle. Much easier to copy the PCB and make a panel with matching holes that way.
